#ifndef __TILE_H__
#define __TILE_H__

enum
{
  LVL1_TILESET = 0,
  LVL2_TILESET,
  LVL3_TILESET,
  LVL4_TILESET,
};

enum
{
  TILE_BLUE_DOOR_EW = 0,
  TILE_RED_DOOR_EW,
  TILE_GREEN_DOOR_EW,
  TILE_WHITE_DOOR_EW,
  TILE_BLUE_DOOR_NS,
  TILE_RED_DOOR_NS,
  TILE_GREEN_DOOR_NS,
  TILE_WHITE_DOOR_NS,
  TILE_LVL1_FLOOR,
  TILE_LVL1_RUG_NW,
  TILE_LVL1_RUG_N,
  TILE_LVL1_RUG_NE,
  TILE_LVL1_WALL,
  TILE_LVL1_RUG_SW,
  TILE_LVL1_RUG_S,
  TILE_LVL1_RUG_SE,
  TILE_LVL1_RAT_HOLE,
};

enum
{
  TILE_GLYPH_WALL       = '#',
  TILE_GLYPH_FLOOR      = '.',
  TILE_GLYPH_RED_DOOR   = 'R',
  TILE_GLYPH_GREEN_DOOR = 'G',
  TILE_GLYPH_BLUE_DOOR  = 'B',
  TILE_GLYPH_WHITE_DOOR = 'W'
};


#endif

